name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.21.x,1.22.x]
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: make build
  
      - name: Test and Coverage
        run: make cover
        
      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: ./tmp/cover.out
  
  license-scan:
    name: License scan
    if: github.repository == 'bartventer/docstore-gen' && github.event_name == 'push'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install FOSSA
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash

      - name: Run FOSSA analyze
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: fossa analyze

      - name: Run FOSSA test
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: fossa test

  semantic-release:
    name: Semantic Release
    needs: [license-scan]
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Run semantic-release
        if: github.repository == 'bartventer/docstore-gen' && github.event_name == 'push'
        run: |
          yarn global add semantic-release@17
          semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
